export const INVENTORY_GRID_CONSTS = {
  SLOT: {
    CONTAINER_SIZE: 100,
    VISUAL_SIZE: 96,
    IMAGE_SIZE: 80,
    BORDER_WIDTH: 3,
    CORNER_RADIUS: 8,
    BACKGROUND_COLOR: "#222222",
    BORDER_COLOR: "#444444"
  },
  DRAG: {
    PREVIEW_BACKGROUND: "#333333",
    PREVIEW_BORDER: "#FFFFFF",
    DROP_TARGET_VALID: "#00FF00",
    DROP_TARGET_INVALID: "#FF0000"
  },
  COUNT: {
    TEXT_SIZE: 24,
    TEXT_COLOR: "#FFFFFF",
    OUTLINE_WIDTH: 3,
    OUTLINE_COLOR: "#000000",
    ELEMENT_SIZE: 24,
    OFFSET_LEFT: 3,
    OFFSET_TOP: -3
  },
  SLOT_NUMBER: {
    ELEMENT_SIZE: 24,
    TEXT_SIZE: 24,
    TEXT_COLOR: "#FFFFFF",
    OFFSET_LEFT: -3,
    OFFSET_TOP: 3
  }
} as const;
